# Generated by Django 5.0.6 on 2024-06-18 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoPais',
            fields=[
                ('id_codigo', models.AutoField(db_column='idCodigo', primary_key=True, serialize=False)),
                ('codigo_pais', models.CharField(max_length=8)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(db_column='idUsuario', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido_paterno', models.CharField(max_length=20)),
                ('apellido_materno', models.CharField(max_length=20)),
                ('rut', models.CharField(max_length=12)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_codigo', models.ForeignKey(db_column='idCodigo', on_delete=django.db.models.deletion.CASCADE, to='appfreelance.codigopais')),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(max_length=50)),
                ('usuario', models.ForeignKey(db_column='idUsuario', on_delete=django.db.models.deletion.CASCADE, to='appfreelance.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('leido', models.BooleanField(default=False)),
                ('proyecto', models.ForeignKey(blank=True, db_column='idProyecto', null=True, on_delete=django.db.models.deletion.CASCADE, to='appfreelance.proyecto')),
                ('destinatario', models.ForeignKey(db_column='idUsuarioDestinatario', on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_recibidos', to='appfreelance.usuario')),
                ('remitente', models.ForeignKey(db_column='idUsuarioRemitente', on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to='appfreelance.usuario')),
            ],
        ),
    ]
