# Generated by Django 5.0.6 on 2024-06-18 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfreelance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripción', models.TextField()),
                ('fecha_oferta', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('pendiente', 'Pendiente')], max_length=50)),
                ('freelancer', models.ForeignKey(db_column='idUsuario', on_delete=django.db.models.deletion.CASCADE, related_name='ofertas_realizadas', to='appfreelance.usuario')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='appfreelance.proyecto')),
            ],
        ),
    ]
