# Generated by Django 5.0.6 on 2024-07-18 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfreelance', '0004_usuario_is_active_usuario_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('freelancer', 'Freelancer'), ('cliente', 'Cliente')], default=12, max_length=10),
            preserve_default=False,
        ),
    ]
