# Generated by Django 5.0.6 on 2024-07-19 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfreelance', '0005_usuario_tipo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('admin', 'Administrador'), ('cliente', 'Cliente')], max_length=10),
        ),
    ]
